// This file is automatically generated using DCOM IDL
// Please do not edit by hand

package proxy

import (
	"bytes"
	uuid "github.com/google/uuid"
	dcom "github.com/michaelrk02/dcom"
	component "github.com/michaelrk02/dcom/example/component"
)

type Employee struct {
	*dcom.ObjectProxy
}

func NewEmployee(instanceID uuid.UUID, conn *dcom.ProxyConnection, f dcom.Factory) dcom.Object {
	return &Employee{ObjectProxy: dcom.NewObjectProxy(instanceID, conn, f)}
}

func (proxy_ *Employee) GetCLSID() uuid.UUID {
	return component.CLSIDEmployee
}

func (proxy_ *Employee) GetName() (string, error) {
	var err_ error
	var params_ bytes.Buffer

	resp_, err_ := proxy_.Conn.InvokeObject(proxy_.GetCLSID(), proxy_.GetInstanceID(), "GetName", &params_)
	if err_ != nil {
		return "", err_
	}

	out_ := dcom.NewDefaultUnmarshaler(resp_)

	errRemote_, err_ := out_.ReadError()
	if err_ != nil {
		return "", err_
	}
	if errRemote_ != nil {
		return "", errRemote_
	}

	var vRemote_ string

	vRemote_, err_ = out_.ReadString()
	if err_ != nil {
		return "", err_
	}

	return vRemote_, errRemote_
}

func (proxy_ *Employee) SetName(name string) error {
	panic("method not exposed")
}

func (proxy_ *Employee) GetSalary() (float64, error) {
	var err_ error
	var params_ bytes.Buffer

	resp_, err_ := proxy_.Conn.InvokeObject(proxy_.GetCLSID(), proxy_.GetInstanceID(), "GetSalary", &params_)
	if err_ != nil {
		return 0.0, err_
	}

	out_ := dcom.NewDefaultUnmarshaler(resp_)

	errRemote_, err_ := out_.ReadError()
	if err_ != nil {
		return 0.0, err_
	}
	if errRemote_ != nil {
		return 0.0, errRemote_
	}

	var vRemote_ float64

	vRemote_, err_ = out_.ReadFloat()
	if err_ != nil {
		return 0.0, err_
	}

	return vRemote_, errRemote_
}

func (proxy_ *Employee) SetSalary(salary float64) error {
	panic("method not exposed")
}

func (proxy_ *Employee) GetTenure() (int, error) {
	var err_ error
	var params_ bytes.Buffer

	resp_, err_ := proxy_.Conn.InvokeObject(proxy_.GetCLSID(), proxy_.GetInstanceID(), "GetTenure", &params_)
	if err_ != nil {
		return 0, err_
	}

	out_ := dcom.NewDefaultUnmarshaler(resp_)

	errRemote_, err_ := out_.ReadError()
	if err_ != nil {
		return 0, err_
	}
	if errRemote_ != nil {
		return 0, errRemote_
	}

	var vRemote_ int

	vRemote_, err_ = out_.ReadInt()
	if err_ != nil {
		return 0, err_
	}

	return vRemote_, errRemote_
}

func (proxy_ *Employee) SetTenure(tenure int) error {
	panic("method not exposed")
}

func (proxy_ *Employee) IsMarried() (bool, error) {
	var err_ error
	var params_ bytes.Buffer

	resp_, err_ := proxy_.Conn.InvokeObject(proxy_.GetCLSID(), proxy_.GetInstanceID(), "IsMarried", &params_)
	if err_ != nil {
		return false, err_
	}

	out_ := dcom.NewDefaultUnmarshaler(resp_)

	errRemote_, err_ := out_.ReadError()
	if err_ != nil {
		return false, err_
	}
	if errRemote_ != nil {
		return false, errRemote_
	}

	var vRemote_ bool

	vRemote_, err_ = out_.ReadBool()
	if err_ != nil {
		return false, err_
	}

	return vRemote_, errRemote_
}

func (proxy_ *Employee) SetMarried(married bool) error {
	panic("method not exposed")
}
